apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: a-release
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
jobs:
  build:
    services:
      redis:
        image: redis
    steps:
      - run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
  format-test-build-publish-deploy:
    needs: build
    services:
      redis:
        image: redis
    steps:
      - run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
  build-2:
    needs: format-test-build-publish-deploy
    steps:
      - run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
  format-test-build-publish-deploy-2:
    needs: build-2
    steps:
      - run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
