apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: a-workflow
on:
  workflow_dispatch:
    inputs:
      param-1:
        type: string
jobs:
  build:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
