apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

env:
  nevironment1: value1
  environment2: value2
  
jobs:
  build:
    steps:
      - name: custom
        uses: custom
        with:
          with1: value1
          with2: value2
