apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: services-workflow
on:
  workflow_dispatch:
jobs:
  build:
    services:
      redis:
        image: redis
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
  format-test-build-publish-deploy:
    needs: build
    services:
      redis:
        image: redis
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
  build-2:
    needs: format-test-build-publish-deploy
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
  format-test-build-publish-deploy-2:
    needs: build-2
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
