apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: service
on:
  workflow_dispatch:
jobs:
  build-build-build-build_build_build-build_build:
    services:
      nginx:
        image: nginx
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
