apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: services-workflow
on:
  workflow_dispatch:
jobs:
  build:
    services:
      redis:
        image: redis
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
  format-test-build-publish-deploy:
    services:
      redis:
        image: redis
    steps:
      - run: echo "Say hello"
        uses: docker://golang:1.20.3-alpine3.17
    needs: build
